In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

# 현재 작업 폴더 기준
BASE_DIR = Path(".")

# 파일 경로
train_path = BASE_DIR / "hanwoo_train" / "hanwoo_train.csv"
weather_path = BASE_DIR / "hanwoo_weather.csv"
area_path = BASE_DIR / "hanwoo_area.csv"
death_path = BASE_DIR / "hanwoo_death.csv"
lineage_path = BASE_DIR / "hanwoo_lineage" / "hanwoo_lineage.csv"

In [3]:
# 한우 도체 등급 판정 데이터
train = pd.read_csv(train_path)

# 기상 데이터
weather = pd.read_csv(weather_path)

# 농장 사육현황 및 면적 데이터
area = pd.read_csv(area_path)

# 농장별 폐사 데이터
death = pd.read_csv(death_path)

# 개체 혈통 데이터
lineage = pd.read_csv(lineage_path)

In [4]:
print("train columns")
print(train.columns.tolist())

print("\nweather columns")
print(weather.columns.tolist())

print("\narea columns")
print(area.columns.tolist())

print("\ndeath columns")
print(death.columns.tolist())

print("\nlineage columns")
print(lineage.columns.tolist())

train columns
['sido', 'sigungu', 'eupmyeondong', 'stn', 'ABATT_DATE', 'JUDGE_DATE', 'JUDGE_SEX', 'WEIGHT', 'BACKFAT', 'REA', 'WINDEX', 'WGRADE', 'INSFAT', 'YUKSAK', 'FATSAK', 'TISSUE', 'GROWTH', 'COST_AMT', 'AGE', 'BIRTH_YMD', 'CATTLE_NO', 'FARM_UNIQUE_NO', 'LAST_GRADE']

weather columns
['stn', 'date', 'ta_max', 'rn_day', 'ta_min', 'rhm_avg', 'ws_davg']

area columns
['FARM_UNIQUE_NO', 'C2023', 'C2024', 'C2025', 'AREA']

death columns
['FARM_UNIQUE_NO', 'BIRTH_YMD', 'DEAD_YMD', 'DEAD_REASON']

lineage columns
['CATTLE_NO', 'KPN_NO', 'FATHER_CATTLE_NO', 'MOTHER_ANIMAL_NO', 'F_GMOTHER_ANIMAL_NO', 'F_GFATHER_CATTLE_NO', 'M_GMOTHER_ANIMAL_NO', 'M_GFATHER_CATTLE_NO']

In [5]:
print("train:", train.shape)
print("weather:", weather.shape)
print("area:", area.shape)
print("death:", death.shape)
print("lineage:", lineage.shape)

train: (2408699, 23)
weather: (973248, 7)
area: (91896, 5)
death: (321389, 4)
lineage: (1809455, 8)

In [6]:
train.head()

,sido,sigungu,eupmyeondong,stn,ABATT_DATE,JUDGE_DATE,JUDGE_SEX,WEIGHT,BACKFAT,REA,...,YUKSAK,FATSAK,TISSUE,GROWTH,COST_AMT,AGE,BIRTH_YMD,CATTLE_NO,FARM_UNIQUE_NO,LAST_GRADE
0,강원특별자치도,정선군,북평면,563,2023-01-01,2023-01-02,암,218,3.0,44.0,...,6.0,7.0,5.0,9.0,-99.0,76,20160915,mI4i8G0BJ8kWD6gdm77RmTzyuIx6N2ZMaZ7wFXx3xb4=,hqh4Qmh5g+ymbYtqjAeKeA==,3B
1,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,520,12.0,100.0,...,5.0,3.0,3.0,3.0,-99.0,32,20200504,tMgfi1p35taO9GH4XN4x0bfO8czy79B8V9NyczRuV+8=,N5qW6dZ91QWCMHg/1kPdlA==,1B
2,경상북도,영주시,이산면,837,2023-01-01,2023-01-02,거세,452,14.0,104.0,...,4.0,3.0,1.0,3.0,-99.0,29,20200803,mdsSD4/sB06U68LNT6P/GUwei2ISyIBZ+R04iLw2mX0=,5UbtU8TgV2yu3Y4/jxuNMQ==,1++B
3,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,454,12.0,95.0,...,5.0,3.0,1.0,3.0,-99.0,32,20200510,LZWd4YatUD851LyC/LFXuxPW7KEXTwVWQONOwqrkLPI=,N5qW6dZ91QWCMHg/1kPdlA==,1++B
4,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,462,10.0,78.0,...,5.0,3.0,3.0,3.0,-99.0,32,20200511,A4FF/dhr8vg7JeW/eqc3922pA69nEaLL/+uoAusZqyU=,N5qW6dZ91QWCMHg/1kPdlA==,1B

In [7]:
weather.head()

   stn        date  ta_max  rn_day  ta_min  rhm_avg  ws_davg
0   95  2020-01-01     0.7     0.0    -9.0     78.4      0.7
1   95  2020-01-02     2.1     0.0    -4.7     87.8      0.7
2   95  2020-01-03     3.3     0.0    -8.4     82.0      0.6
3   95  2020-01-04     5.2     0.0    -9.7     79.3      0.6
4   95  2020-01-05     5.3     0.0   -10.4     78.3      0.5

In [8]:
area.head()

             FARM_UNIQUE_NO  C2023  C2024  C2025    AREA
0  X8bGdfHedF2o5xSAAERtEA==   23.0   26.0   25.0  220.00
1  N9t4B2mc+EZsH7wBLT8U4Q==   37.0   34.0   32.0  431.05
2  DeEu4RIkIUXq7NyTBwD8vg==   10.0    5.0    3.0  265.82
3  fgQkQJ+iyrFZDHsC9ih9mQ==   35.0   41.0   40.0  593.80
4  2mUAsXfTviEJtFBM7s31uw==   16.0   14.0   15.0  155.61

In [9]:
death.head()

             FARM_UNIQUE_NO  BIRTH_YMD  DEAD_YMD DEAD_REASON
0  WiJdwGdfb+CC7Jg0Pn/aLA==   20070621  20250107         -99
1  gj6CI5LHYXz7druWs1ZEUQ==   20060705  20250106         -99
2  We6zq4c9yoG5GKrt1CbrdA==   20080610  20250103         -99
3  s67fGrSPXhX1Bgp+JDW9Aw==   20050408  20250108         -99
4  3lGF4dGtWtydlceogBluUA==   20080425  20250109         -99

In [10]:
lineage.head()

,CATTLE_NO,KPN_NO,FATHER_CATTLE_NO,MOTHER_ANIMAL_NO,F_GMOTHER_ANIMAL_NO,F_GFATHER_CATTLE_NO,M_GMOTHER_ANIMAL_NO,M_GFATHER_CATTLE_NO
0,yaSF9EHVPBIFeOdxL/st19so274mMHAbxmME5JhQ0Jk=,mgzxMpKRCOrwfHqsCHzP47qdLKwCfR8ULPzyRiJVOkM=,AMohGlr/7kUmTZcSjmBDCZP7fGvHMGm2uWw51JIprKc=,cMfffVbj3vfDem0QlY2ZOZphrIldXYc+f60y3Hvq9nI=,efoeB0IMVAIi87aCUIsPhGDfry4wx/cULq0c7MLKFA4=,SgXkbJ+3aQWEQl4EoT96zIyQAo5tEjvHfdMR2mvaVXw=,wV9qjXaPXOkYKpKj9nip78T5MB5AVUSkcK5tDT5O8e0=,Pd9ODUb0XUGA5X8xdQ5AdlNZk4cl7vCd/UfKUhXezYk=
1,iCeTx0O5z/M8GAcglblMDFVCzmvnkdPVRKTQtIN4ZFg=,mgzxMpKRCOrwfHqsCHzP47qdLKwCfR8ULPzyRiJVOkM=,AMohGlr/7kUmTZcSjmBDCZP7fGvHMGm2uWw51JIprKc=,0JDDs8FOPj0ZsxNi8H9ko/sBDa3eRTB9bq4nbuhtcpY=,efoeB0IMVAIi87aCUIsPhGDfry4wx/cULq0c7MLKFA4=,SgXkbJ+3aQWEQl4EoT96zIyQAo5tEjvHfdMR2mvaVXw=,SKOzaLpnj/ojtvXerWQzc1HSyU2kDhtQ42ShRDVA+/8=,Gt6xHYYq6gyhiQ2S6czPsYfvPNtj7D/O/Tw7yzi4e5w=
2,vI7joD/5v0T+wqvjC0d/36Sv5y+9NG18W+y2/YRVllg=,KDcckdOdPX/Uve2c5f7RNbAQrB27wyafOtzqX260DT4=,FXlabyH9KcP+VEzuDdo2xilVUs4PIl83AVIsv3AWiNc=,u6rUplX8Xi7ldmcYV1+AVtyCkMZLao7JzGOBuD1COMU=,Z7eNcRWyZHwpzEUJhPMNvbajt2EK/v1qGltu/05jQNw=,xJEKH2EwTkJaR/ajqNUgMSSlHOxsrEXijgN2Er6PBFo=,kluWj1LiM8I6nYWfDenO7q4tJySB2AVV8z9cMqweuXA=,kluWj1LiM8I6nYWfDenO7q4tJySB2AVV8z9cMqweuXA=
3,j0URLNNWbjl9ypDnsdULQAhvQ4roRAFjP0kGszyEXXw=,PBpDKzobFwTYitup5cJrqGpOK6iVZJvV6r42rmEbbZY=,A+eYuVUY8/QwN4+Ddgs7Tvko8TjAN7AtZv2+aZy0xIc=,fvUhHnLXiy3xTVKmqY62z+s5RlegNhPaR9ex1Gx0eN0=,+qwqADxeX1176gNXAgnIZjCeAdxDM1LrO3pn87MdVzA=,6LFovs6S310gxvJaixkryaO54hmEUBGq2C/pHCgq2No=,Ck6/PtPWiRKlWc9/jjgKjpepUIaUD2NlOlYzbbEzSOs=,Ju4e/qNWdk0qXYEO/m2Ypv7BGAwqhScFw+zq9k+mjKU=
4,kOnOAfd4lRrulCE9uv9ekwUcP/W9Hs41K1i5U0OLAfo=,+mx1i1sOZ7tc0lLUnrEQjGghLy+l5BH5XrTmY72A9Zc=,mAaX9QxFXASjT6u+keurKA90ZDThZfQ5xJzY6bv/6/8=,f7xH6ZSCkAVcPimjhYi5OqHYDXTX8GxNo+R7GeJYQ0s=,hyumffzX44tVUGJ22AnMUaD3t+jU7DWWPeGQzzrAQM8=,PJRSI2aIwE+wgp9nIHhFVxIm2gDfLdmeDbdUjDsn4GI=,FhYpc9/PEsQfoBSv2l3Ihz8r96yhBvEWup1GsUjhvXY=,H0hzRqFLWYoL0ncDgFrEGDeHw//E0XvfVXSi749m7Iw=

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2408699 entries, 0 to 2408698
Data columns (total 23 columns):
 #   Column          Dtype
---  ------          -----
 0   sido            object
 1   sigungu         object
 2   eupmyeondong    object
 3   stn             int64
 4   ABATT_DATE      object
 5   JUDGE_DATE      object
 6   JUDGE_SEX       object
 7   WEIGHT          int64
 8   BACKFAT         float64
 9   REA             float64
 10  WINDEX          float64
 11  WGRADE          object
 12  INSFAT          float64
 13  YUKSAK          float64
 14  FATSAK          float64
 15  TISSUE          float64
 16  GROWTH          float64
 17  COST_AMT        float64
 18  AGE             int64
 19  BIRTH_YMD       int64
 20  CATTLE_NO       object
 21  FARM_UNIQUE_NO  object
 22  LAST_GRADE      object
dtypes: float64(9), int64(4), object(10)
memory usage: 422.7+ MB

## 결측치 확인

In [12]:
import pandas as pd

files = {
    "hanwoo_area": "hanwoo_area.csv",
    "hanwoo_weather": "hanwoo_weather.csv",
    "hanwoo_death": "hanwoo_death.csv",
    "hanwoo_train": "hanwoo_train/hanwoo_train.csv",
    "hanwoo_lineage": "hanwoo_lineage/hanwoo_lineage.csv"
}

for name, path in files.items():
    print("=" * 50)
    print(name)

    df = pd.read_csv(path)

    # 진짜 빈값 개수
    missing_count = df.isna().sum().sum()
    shape = df.shape

    # -99 개수
    minus99_count = (df.astype(str) == "-99").sum().sum()
    print("행,열 개수:", shape)
    print("빈값 개수:", missing_count)
    print("-99 개수:", minus99_count)
    print("빈값 + -99 개수:", missing_count + minus99_count)

==================================================
hanwoo_area
행,열 개수: (91896, 5)
빈값 개수: 0
-99 개수: 0
빈값 + -99 개수: 0
==================================================
hanwoo_weather
행,열 개수: (973248, 7)
빈값 개수: 0
-99 개수: 0
빈값 + -99 개수: 0
==================================================
hanwoo_death
행,열 개수: (321389, 4)
빈값 개수: 0
-99 개수: 234276
빈값 + -99 개수: 234276
==================================================
hanwoo_train
행,열 개수: (2408699, 23)
빈값 개수: 0
-99 개수: 0
빈값 + -99 개수: 0
==================================================
hanwoo_lineage
행,열 개수: (1809455, 8)
빈값 개수: 0
-99 개수: 4490
빈값 + -99 개수: 4490

In [13]:
death['DEAD_REASON'].value_counts()

DEAD_REASON
-99                                234276
설사                                   8230
우결핵                                  4479
브루셀라 살처분                             3456
설사병                                  3378
                                    ...
비닐을 먹고 식도가 막힘                           1
알빠짐                                     1
만성폐렴에 의한 호흡곤란                           1
피설사로 인해 폐사                              1
4위식체로 인한 위 내용물 과다 저류로 복강장기 압박 등         1
Name: count, Length: 12809, dtype: int64

In [14]:
death["FARM_UNIQUE_NO"].value_counts()

FARM_UNIQUE_NO
OFiqGqbXY6mVRUYejssPWQ==    767
ozvZ+5yHyfJucRanowMULg==    547
WdmUAmHE/YrtMPE/3AILSQ==    511
c7WF0ILQ00QOp3MWGYgGJA==    454
QeHBdV2MKMLB6fGFE5eqHg==    401
                           ...
aQmGPEed6QgcFSMzFjkqaQ==      1
p9gNxZ2MCVXJrqoLLsuXjQ==      1
UaoGa0IyWNTkVLO9d+31Ag==      1
WhUUde16mUVb2yw/0+pBXQ==      1
QI339S8YmOxDk+YM4o1vIw==      1
Name: count, Length: 50623, dtype: int64

In [15]:
train

,sido,sigungu,eupmyeondong,stn,ABATT_DATE,JUDGE_DATE,JUDGE_SEX,WEIGHT,BACKFAT,REA,...,YUKSAK,FATSAK,TISSUE,GROWTH,COST_AMT,AGE,BIRTH_YMD,CATTLE_NO,FARM_UNIQUE_NO,LAST_GRADE
0,강원특별자치도,정선군,북평면,563,2023-01-01,2023-01-02,암,218,3.0,44.0,...,6.0,7.0,5.0,9.0,-99.0,76,20160915,mI4i8G0BJ8kWD6gdm77RmTzyuIx6N2ZMaZ7wFXx3xb4=,hqh4Qmh5g+ymbYtqjAeKeA==,3B
1,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,520,12.0,100.0,...,5.0,3.0,3.0,3.0,-99.0,32,20200504,tMgfi1p35taO9GH4XN4x0bfO8czy79B8V9NyczRuV+8=,N5qW6dZ91QWCMHg/1kPdlA==,1B
2,경상북도,영주시,이산면,837,2023-01-01,2023-01-02,거세,452,14.0,104.0,...,4.0,3.0,1.0,3.0,-99.0,29,20200803,mdsSD4/sB06U68LNT6P/GUwei2ISyIBZ+R04iLw2mX0=,5UbtU8TgV2yu3Y4/jxuNMQ==,1++B
3,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,454,12.0,95.0,...,5.0,3.0,1.0,3.0,-99.0,32,20200510,LZWd4YatUD851LyC/LFXuxPW7KEXTwVWQONOwqrkLPI=,N5qW6dZ91QWCMHg/1kPdlA==,1++B
4,강원특별자치도,평창군,진부면,560,2023-01-01,2023-01-02,거세,462,10.0,78.0,...,5.0,3.0,3.0,3.0,-99.0,32,20200511,A4FF/dhr8vg7JeW/eqc3922pA69nEaLL/+uoAusZqyU=,N5qW6dZ91QWCMHg/1kPdlA==,1B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2408694,강원특별자치도,강릉시,경포동,105,2025-12-30,2025-12-31,거세,501,27.0,83.0,...,5.0,3.0,1.0,3.0,-99.0,30,20230703,+FszTalO8Vu4egWG99M0uQ6E2cUjzFUYLcCL7AE+4xY=,uRm4kiEg2sbBqAK/0NGk9w==,1++C
2408695,강원특별자치도,강릉시,강동면,105,2025-12-30,2025-12-31,거세,376,10.0,83.0,...,5.0,3.0,2.0,3.0,-99.0,31,20230619,Jc1HEH+HwrdoJxndeGVpp4FmJlyu7oy2z7Db63pJ998=,5qHgnC8C7q1VrYtPwSqzYw==,1A
2408696,강원특별자치도,강릉시,경포동,105,2025-12-30,2025-12-31,거세,419,13.0,86.0,...,6.0,3.0,3.0,2.0,-99.0,28,20230914,C2cZO2sVzKp0PqO7iidSR59zIu1XPw1QmE2LjEA8JW8=,uRm4kiEg2sbBqAK/0NGk9w==,2B
2408697,강원특별자치도,강릉시,강동면,105,2025-12-30,2025-12-31,거세,430,13.0,97.0,...,4.0,3.0,1.0,2.0,-99.0,28,20230926,HFxwAB/Eqh750engl4kMiYTXpFJZDeAPGAcdcnRiAWw=,5qHgnC8C7q1VrYtPwSqzYw==,1++B
2408698,강원특별자치도,철원군,서면,552,2025-12-30,2025-12-31,거세,399,13.0,92.0,...,4.0,3.0,3.0,2.0,-99.0,20,20240519,JAMW+s1VS5GEHozRa7fxWRv2cUd7IELnimYbyWwLqmQ=,RHTN5w//QPnT6CdTpEoCmw==,1B